### ISSUE TITLE
You may need an appropriate loader ...

### ISSUE THREAD

**Issue by manodupont** [didierfranc/react-code-splitting#8]
I always got this.

```
Module parse failed: /Users/manueldupont/test/avid-sibelius-publishing-viewer/node_modules/babel-loader/lib/index.js?{"cacheDirectory":true,"babelrc":false,"presets":["react","es2015","stage-0"],"plugins":["transform-runtime",["transform-react-remove-prop-types","transform-react-constant-elements","transform-react-inline-elements"]]}!/Users/manueldupont/test/avid-sibelius-publishing-viewer/src/components/App/App.js Unexpected token (110:77)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (110:77)
        at Parser.pp$4.raise (/Users/manueldupont/test/avid-sibelius-publishing-viewer/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
        at Parser.pp.unexpected (/Users/manueldupont/test/avid-sibelius-publishing-viewer/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (/Users/manueldupont/test/avid-sibelius-publishing-
```

I can't find why

here is my loader : 

```
module: {
    loaders: [
      {
        test: /\.(js|jsx)$/,
        loader: 'babel-loader',
        include: [
          path.resolve(__dirname, '../node_modules/react-routing/src'),
          path.resolve(__dirname, '../src'),
        ],
...
```

**Comment by neoziro** [comment]
The problem is probably relative to your babel configuration, you may need ["env"](https://babeljs.io/docs/plugins/preset-env/) and ["react"](https://babeljs.io/docs/plugins/preset-react/) preset to make it work.
